# Generated by Django 2.1.5 on 2020-08-01 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200729_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=8)),
                ('date', models.DateField()),
                ('prediction_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prediction_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prediction_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prediction_4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prediction_5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prediction_6', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prediction_7', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence_lower', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('confidence_upper', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('temperature', models.CharField(blank=True, max_length=5)),
                ('rainfall', models.CharField(blank=True, max_length=5)),
                ('economy_indicator', models.BooleanField(blank=True)),
                ('cotton_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CottonType')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Market')),
            ],
        ),
    ]
