# Generated by Django 2.1.5 on 2020-08-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='cotton_type',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='market',
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
