# Generated by Django 2.1.5 on 2020-08-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200802_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
