# Generated by Django 2.1.5 on 2020-08-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200802_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('Farmer', 'Farmer'), ('Ministry', 'Ministry')], default='Customer', max_length=10),
        ),
    ]
