name: sih_cotton
description: A new Flutter project.

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.0
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0
  cached_network_image: ^2.0.0-rc
  shared_preferences: ^0.5.3+4
  built_value: ^6.2.0
  cupertino_icons: ^0.1.3
  provider: ^4.1.3
  flutter_launcher_icons: ^0.7.5
  translator: ^0.1.5
  charts_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  built_value_generator: ^6.2.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/logo_transparent.png"
  image_path_ios: "assets/images/logo.png"
  adaptive_icon_background: "#FFB7CE62"
  adaptive_icon_foreground: "assets/images/logo_transparent.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: PTSans
      fonts:
        - asset: assets/fonts/PTSans-Regular.ttf
        - asset: assets/fonts/PTSans-Bold.ttf
        - asset: assets/fonts/PTSans-Italic.ttf
        - asset: assets/fonts/PTSans-BoldItalic.ttf
