from api.models import Analysis, CottonType, Market

CottonTypes = [
    "American",
    "Other",
    "MCU",
    "Cotton",
    "Shanker",
    "F",
    "LH",
    "GCH",
    "Desi",
    "LRA",
    "DCH",
    "H.B",
    "H",
]

for ct in CottonTypes:
    CottonType.objects.create(name=ct)

Markets = [
    ["Gujarat", "Ahmedabad", "Dhandhuka"],
    ["Gujarat", "Amreli", "Amreli"],
    ["Gujarat", "Amreli", "Babra"],
    ["Gujarat", "Amreli", "Bagasara"],
    ["Gujarat", "Bhavnagar", "Bhavnagar"],
    ["Gujarat", "Bhavnagar", "Botad(Haddad)"],
    ["Gujarat", "Bhavnagar", "Mahuva(Station Road)"],
    ["Gujarat", "Jamnagar", "Dhrol"],
    ["Gujarat", "Jamnagar", "Jamnagar"],
    ["Gujarat", "Junagarh", "Manavdar"],
    ["Gujarat", "Junagarh", "Visavadar"],
    ["Gujarat", "Kheda", "Kapadvanj"],
    ["Gujarat", "Mehsana", "Unava"],
    ["Gujarat", "Mehsana", "Visnagar"],
    ["Gujarat", "Morbi", "Vankaner"],
    ["Gujarat", "Patan", "Patan"],
    ["Gujarat", "Rajkot", "Dhoraji"],
    ["Gujarat", "Rajkot", "Gondal"],
    ["Gujarat", "Rajkot", "Jetpur(Dist.Rajkot)"],
    ["Gujarat", "Sabarkantha", "Bhiloda"],
    ["Gujarat", "Surendranagar", "Chotila"],
    ["Gujarat", "Surendranagar", "Halvad"],
    ["Gujarat", "Surendranagar", "Limdi"],
    ["Gujarat", "Vadodara(Baroda)", "Bodeli"],
    ["Gujarat", "Vadodara(Baroda)", "Bodeli(Hadod)"],
    ["Gujarat", "Vadodara(Baroda)", "Bodeli(Kalediya)"],
    ["Gujarat", "Vadodara(Baroda)", "Bodeli(Modasar)"],
    ["Gujarat", "Vadodara(Baroda)", "Karjan"],
    ["Haryana", "Fatehabad", "Bhattu Kalan"],
    ["Haryana", "Jind", "Uchana"],
    ["Haryana", "Sirsa", "Ding"],
    ["Haryana", "Sirsa", "Sirsa_Haryana"],
    ["Karnataka", "Bijapur", "Bijapur"],
    ["Karnataka", "Davangere", "Davangere"],
    ["Karnataka", "Dharwad", "Annigeri"],
    ["Karnataka", "Dharwad", "Hubli (Amaragol)"],
    ["Karnataka", "Haveri", "Haveri"],
    ["Karnataka", "Haveri", "Ranebennur"],
    ["Karnataka", "Haveri", "Savanur"],
    ["Karnataka", "Raichur", "Raichur"],
    ["Madhya Pradesh", "Alirajpur", "Jobat"],
    ["Madhya Pradesh", "Badwani", "Balwadi"],
    ["Madhya Pradesh", "Badwani", "Khetia"],
    ["Madhya Pradesh", "Badwani", "Sendhwa"],
    ["Madhya Pradesh", "Chhindwara", "Pandhurna"],
    ["Madhya Pradesh", "Chhindwara", "Saunsar"],
    ["Madhya Pradesh", "Jhabua", "Jhabua"],
    ["Maharashtra", "Beed", "Kille Dharur"],
    ["Maharashtra", "Chandrapur", "Rajura"],
    ["Maharashtra", "Nagpur", "Kalmeshwar"],
    ["Maharashtra", "Nagpur", "Narkhed"],
    ["Maharashtra", "Nanded", "Bhokar"],
    ["Maharashtra", "Parbhani", "Parbhani"],
    ["Maharashtra", "Wardha", "Arvi"],
    ["Maharashtra", "Wardha", "Pulgaon"],
    ["Punjab", "Muktsar", "Malout"],
    ["Rajasthan", "Ajmer", "Kekri"],
    ["Rajasthan", "Alwar", "Khairthal"],
    ["Rajasthan", "Ganganagar", "Anoopgarh"],
    ["Rajasthan", "Ganganagar", "Gajsinghpur"],
    ["Rajasthan", "Ganganagar", "Gharsana"],
    ["Rajasthan", "Ganganagar", "Jaitsar"],
    ["Rajasthan", "Ganganagar", "Padampur_Rajasthan"],
    ["Rajasthan", "Ganganagar", "Raisingh Nagar"],
    ["Rajasthan", "Ganganagar", "Rawla"],
    ["Rajasthan", "Ganganagar", "Sadulshahar"],
    ["Rajasthan", "Ganganagar", "Sri Karanpur"],
    ["Rajasthan", "Ganganagar", "Sri Vijayanagar"],
    ["Rajasthan", "Ganganagar", "Sriganganagar"],
    ["Rajasthan", "Hanumangarh", "Goluwala"],
    ["Rajasthan", "Hanumangarh", "Hanumangarh"],
    ["Rajasthan", "Hanumangarh", "Pilli Banga"],
    ["Rajasthan", "Hanumangarh", "Rawatsar"],
    ["Rajasthan", "Hanumangarh", "Sangriya"],
    ["Rajasthan", "Hanumangarh", "Suratgarh"],
    ["Rajasthan", "Jodhpur", "Bilara"],
    ["Tamil Nadu", "Madurai", "Thirumangalam"],
    ["Tamil Nadu", "Madurai", "Usilampatty"],
    ["Tamil Nadu", "Salem", "Kolathur"],
    ["Tamil Nadu", "Salem", "Konganapuram"],
    ["Tamil Nadu", "Villupuram", "Vikkiravandi"],
    ["Tamil Nadu", "Villupuram", "Villupuram"],
    ["Telangana", "Adilabad", "Adilabad"],
    ["Telangana", "Adilabad", "Asifabad"],
    ["Telangana", "Adilabad", "Indravelly(Utnoor)"],
    ["Telangana", "Adilabad", "Kuber"],
    ["Telangana", "Karimnagar", "Choppadandi"],
    ["Telangana", "Karimnagar", "Karimnagar"],
    ["Telangana", "Khammam", "Enkoor"],
    ["Telangana", "Khammam", "Khammam"],
    ["Telangana", "Khammam", "Kothagudem"],
    ["Telangana", "Warangal", "Jangaon"],
    ["Telangana", "Warangal", "Narsampet"],
    ["Telangana", "Warangal", "Parkal"],
    ["Telangana", "Warangal", "Warangal"],
]

for m in Markets:
    Market.objects.create(name=m[2], state=m[0], district=m[1])

Market_Types = [
    ["Adilabad", "Cotton"],
    ["Amreli", "Other"],
    ["Annigeri", "GCH"],
    ["Anoopgarh", "American"],
    ["Arvi", "H"],
    ["Asifabad", "Cotton"],
    ["Babra", "Shanker"],
    ["Bagasara", "Other"],
    ["Balwadi", "H"],
    ["Bhattu Kalan", "American"],
    ["Bhavnagar", "Other"],
    ["Bhiloda", "Other"],
    ["Bhokar", "Other"],
    ["Bijapur", "LH"],
    ["Bilara", "Other"],
    ["Bodeli", "Shanker"],
    ["Bodeli(Hadod)", "Shanker"],
    ["Bodeli(Kalediya)", "Shanker"],
    ["Bodeli(Modasar)", "Shanker"],
    ["Botad(Haddad)", "Shanker"],
    ["Choppadandi", "Cotton"],
    ["Chotila", "Shanker"],
    ["Davangere", "MCU"],
    ["Dhandhuka", "Shanker"],
    ["Dhoraji", "H.B"],
    ["Dhrol", "Other"],
    ["Ding", "American"],
    ["Enkoor", "Cotton"],
    ["Gajsinghpur", "American"],
    ["Gharsana", "American"],
    ["Goluwala", "American"],
    ["Goluwala", "Desi"],
    ["Gondal", "H.B"],
    ["Halvad", "Other"],
    ["Hanumangarh", "Desi"],
    ["Haveri", "GCH"],
    ["Hubli (Amaragol)", "GCH"],
    ["Indravelly(Utnoor)", "Cotton"],
    ["Jaitsar", "American"],
    ["Jamnagar", "Other"],
    ["Jangaon", "Cotton"],
    ["Jetpur(Dist.Rajkot)", "Cotton"],
    ["Jhabua", "DCH"],
    ["Jobat", "Other"],
    ["Kalmeshwar", "Other"],
    ["Kapadvanj", "Other"],
    ["Karimnagar", "Cotton"],
    ["Karjan", "Shanker"],
    ["Kekri", "Other"],
    ["Khairthal", "Other"],
    ["Khammam", "Cotton"],
    ["Khetia", "H"],
    ["Kille Dharur", "Other"],
    ["Kolathur", "Other"],
    ["Konganapuram", "Other"],
    ["Kothagudem", "Cotton"],
    ["Kuber", "Cotton"],
    ["Limdi", "Shanker"],
    ["Mahuva(Station Road)", "Shanker"],
    ["Malout", "Other"],
    ["Manavdar", "Shanker"],
    ["Narkhed", "Other"],
    ["Narsampet", "Cotton"],
    ["Padampur_Rajasthan", "American"],
    ["Pandhurna", "Other"],
    ["Parbhani", "Other"],
    ["Parkal", "Cotton"],
    ["Patan", "Other"],
    ["Pilli Banga", "American"],
    ["Pilli Banga", "Desi"],
    ["Pulgaon", "Other"],
    ["Raichur", "F"],
    ["Raisingh Nagar", "American"],
    ["Rajura", "Other"],
    ["Ranebennur", "GCH"],
    ["Rawatsar", "American"],
    ["Rawla", "American"],
    ["Sadulshahar", "American"],
    ["Sangriya", "Other"],
    ["Saunsar", "H"],
    ["Savanur", "GCH"],
    ["Sendhwa", "H"],
    ["Sirsa_Haryana", "American"],
    ["Sri Karanpur", "American"],
    ["Sri Vijayanagar", "American"],
    ["Sri Vijayanagar", "Desi"],
    ["Sriganganagar", "American"],
    ["Suratgarh", "American"],
    ["Thirumangalam", "MCU"],
    ["Thirumangalam", "Other"],
    ["Uchana", "American"],
    ["Unava", "Other"],
    ["Usilampatty", "LRA"],
    ["Usilampatty", "MCU"],
    ["Usilampatty", "Other"],
    ["Vankaner", "Other"],
    ["Vikkiravandi", "Other"],
    ["Villupuram", "Other"],
    ["Visavadar", "Other"],
    ["Visnagar", "Other"],
    ["Warangal", "Cotton"],
]


# Data for Analysis


market = "Adilabad"
cotton_type = "Cotton"
predictions = {
    "Daily": {
        "30/07/2020": {
            "Forecast_Price": "3890.22",
            "Lower_Bound": "2728.66",
            "Upper_Bound": "5051.78",
        },
        "31/07/2020": {
            "Forecast_Price": "3895.58",
            "Lower_Bound": "2994.70",
            "Upper_Bound": "4796.45",
        },
        "01/08/2020": {
            "Forecast_Price": "3842.49",
            "Lower_Bound": "2782.33",
            "Upper_Bound": "4902.65",
        },
        "02/08/2020": {
            "Forecast_Price": "3832.53",
            "Lower_Bound": "2729.19",
            "Upper_Bound": "4935.88",
        },
        "03/08/2020": {
            "Forecast_Price": "3852.48",
            "Lower_Bound": "2666.35",
            "Upper_Bound": "5038.61",
        },
        "04/08/2020": {
            "Forecast_Price": "3987.07",
            "Lower_Bound": "3097.97",
            "Upper_Bound": "4876.17",
        },
        "05/08/2020": {
            "Forecast_Price": "3896.33",
            "Lower_Bound": "2924.10",
            "Upper_Bound": "4868.57",
        },
    },
    "Weekly": {
        "07/08/2020": {
            "Forecast_Price": "4868.40",
            "Lower_Bound": "2299.92",
            "Upper_Bound": "7436.88",
        },
        "14/08/2020": {
            "Forecast_Price": "4843.38",
            "Lower_Bound": "2282.02",
            "Upper_Bound": "7404.74",
        },
        "21/08/2020": {
            "Forecast_Price": "4850.71",
            "Lower_Bound": "2288.67",
            "Upper_Bound": "7412.75",
        },
        "28/08/2020": {
            "Forecast_Price": "4930.42",
            "Lower_Bound": "2385.26",
            "Upper_Bound": "7475.59",
        },
        "04/09/2020": {
            "Forecast_Price": "4868.92",
            "Lower_Bound": "2300.00",
            "Upper_Bound": "7437.83",
        },
        "11/09/2020": {
            "Forecast_Price": "4863.69",
            "Lower_Bound": "2292.14",
            "Upper_Bound": "7435.24",
        },
        "18/09/2020": {
            "Forecast_Price": "4861.91",
            "Lower_Bound": "2290.42",
            "Upper_Bound": "7433.40",
        },
    },
    "Monthly": {
        "30/08/2020": {
            "Forecast_Price": "4765.20",
            "Lower_Bound": "2404.20",
            "Upper_Bound": "7126.21",
        },
        "29/09/2020": {
            "Forecast_Price": "4706.20",
            "Lower_Bound": "2368.22",
            "Upper_Bound": "7044.18",
        },
        "29/10/2020": {
            "Forecast_Price": "4694.47",
            "Lower_Bound": "2353.81",
            "Upper_Bound": "7035.14",
        },
        "28/11/2020": {
            "Forecast_Price": "4758.55",
            "Lower_Bound": "2420.19",
            "Upper_Bound": "7096.90",
        },
        "28/12/2020": {
            "Forecast_Price": "4806.03",
            "Lower_Bound": "2468.42",
            "Upper_Bound": "7143.64",
        },
        "27/01/2021": {
            "Forecast_Price": "4808.76",
            "Lower_Bound": "2468.46",
            "Upper_Bound": "7149.06",
        },
        "26/02/2021": {
            "Forecast_Price": "4791.33",
            "Lower_Bound": "2449.63",
            "Upper_Bound": "7133.02",
        },
    },
}

market = "Annigeri"
cotton_type = "GCH"
predictions = {
    "Daily": {
        "30/07/2020": {
            "Forecast_Price": "4316.93",
            "Lower_Bound": "3470.74",
            "Upper_Bound": "5163.13",
        },
        "31/07/2020": {
            "Forecast_Price": "4293.66",
            "Lower_Bound": "3282.38",
            "Upper_Bound": "5304.93",
        },
        "01/08/2020": {
            "Forecast_Price": "5151.74",
            "Lower_Bound": "3485.57",
            "Upper_Bound": "6817.91",
        },
        "02/08/2020": {
            "Forecast_Price": "3522.13",
            "Lower_Bound": "1127.94",
            "Upper_Bound": "5916.33",
        },
        "03/08/2020": {
            "Forecast_Price": "4694.45",
            "Lower_Bound": "2768.87",
            "Upper_Bound": "6620.02",
        },
        "04/08/2020": {
            "Forecast_Price": "4590.32",
            "Lower_Bound": "3740.88",
            "Upper_Bound": "5439.76",
        },
        "05/08/2020": {
            "Forecast_Price": "5029.09",
            "Lower_Bound": "4291.10",
            "Upper_Bound": "5767.07",
        },
    },
    "Weekly": {
        "07/08/2020": {
            "Forecast_Price": "4520.73",
            "Lower_Bound": "3350.56",
            "Upper_Bound": "5690.91",
        },
        "14/08/2020": {
            "Forecast_Price": "4569.64",
            "Lower_Bound": "3339.44",
            "Upper_Bound": "5799.84",
        },
        "21/08/2020": {
            "Forecast_Price": "4639.98",
            "Lower_Bound": "3401.31",
            "Upper_Bound": "5878.65",
        },
        "28/08/2020": {
            "Forecast_Price": "4700.40",
            "Lower_Bound": "3457.16",
            "Upper_Bound": "5943.64",
        },
        "04/09/2020": {
            "Forecast_Price": "4776.56",
            "Lower_Bound": "3516.47",
            "Upper_Bound": "6036.64",
        },
        "11/09/2020": {
            "Forecast_Price": "4870.64",
            "Lower_Bound": "3586.20",
            "Upper_Bound": "6155.07",
        },
        "18/09/2020": {
            "Forecast_Price": "4941.87",
            "Lower_Bound": "3641.28",
            "Upper_Bound": "6242.45",
        },
    },
    "Monthly": {
        "30/08/2020": {
            "Forecast_Price": "4021.84",
            "Lower_Bound": "2599.98",
            "Upper_Bound": "5443.71",
        },
        "29/09/2020": {
            "Forecast_Price": "4981.82",
            "Lower_Bound": "4340.79",
            "Upper_Bound": "5622.85",
        },
        "29/10/2020": {
            "Forecast_Price": "979.17",
            "Lower_Bound": "-3037.83",
            "Upper_Bound": "4996.16",
        },
        "28/11/2020": {
            "Forecast_Price": "13790.50",
            "Lower_Bound": "7291.56",
            "Upper_Bound": "20289.43",
        },
        "28/12/2020": {
            "Forecast_Price": "-23187.26",
            "Lower_Bound": "-47138.58",
            "Upper_Bound": "764.06",
        },
        "27/01/2021": {
            "Forecast_Price": "92630.66",
            "Lower_Bound": "21334.42",
            "Upper_Bound": "163926.89",
        },
        "26/02/2021": {
            "Forecast_Price": "-298123.19",
            "Lower_Bound": "-548358.46",
            "Upper_Bound": "-47887.93",
        },
    },
}

# For populating Analysis Table
import datetime
from api.models import Market, CottonType, Analysis

for i in range(len(Market_Types)):
    predictions = PREDICTIONS[i]
    market = Market_Types[i][0]
    cotton_type = Market_Types[i][1]
    for period in predictions:
        for date in predictions[period]:
            Analysis.objects.create(
                cotton_type=CottonType.objects.filter(name=cotton_type)[0],
                market=Market.objects.filter(name=market)[0],
                period=period,
                date=datetime.datetime.strptime(date, "%d/%m/%Y").strftime("%Y-%m-%d"),
                prediction=predictions[period][date]["Forecast_Price"],
                confidence_lower=predictions[period][date]["Lower_Bound"],
                confidence_upper=predictions[period][date]["Upper_Bound"],
            )
